baseURL = 'https://owen-stanclift.github.io/'
languageCode = 'en-us'
title = 'Owen Stanclift'
theme = 'mana' 

[caches]
  [caches.images]
    dir = ':cacheDir/images'
 
[params]
  description = "Owen Stanclift's Game Programmer Portfolio"
  favicon = "/favicon/favicon.ico"
  footerText = "Built with Hugo and Mana theme"  # Optional
  
  # Hero section title (optional - defaults to site.Title)
  heroTitleLine1 = "Owen"  # First line of hero title
  heroTitleLine2 = "Stanclift"    # Second line of hero title (optional)

 # Custom message for the 404 error page (supports HTML)
  # If not set, defaults to: "Sorry, the page you are looking for could not be found."
  custom404Message = "Sorry, the page you are looking for could not be found. I guess I don't have a guide for <em>everything</em>"

[params.avatar]
  url = "https://media.licdn.com/dms/image/v2/D4E03AQF_Uzwf8KfbHw/profile-displayphoto-scale_400_400/B4EZxOkEoFK0Ak-/0/1770844605470?e=1772668800&v=beta&t=f03upFgi4uocfcTEtzQiLuNHr8DwO5BQ2n74x5N2gIw"

[params.social]
  github = "https://github.com/yourusername"
  linkedin = "https://www.linkedin.com/in/yourprofile"
  email = "your.email@example.com"

[[menus.main]]
  name = 'Home'
  pageRef = '/'
  weight = 10

[[menus.main]]
  name = 'Projects'
  pageRef = '/projects/'
  weight = 20

[[menus.main]]
  name = 'Resume'
  pageRef = '/resume/'
  weight = 30

[[menus.main]]
  name = 'About'
  pageRef = '/about/'
  weight = 40

[pagination]
  pageSize = 10  # Number of posts per page (default: 10)

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false
  [markup.goldmark]
    [markup.goldmark.parser]
      # Enable block-level attributes for blockquotes
      [markup.goldmark.parser.attribute]
        block = true
        title = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    style = "catppuccin-macchiato"  # Default style

  [params.codeHighlight]
    darkTheme = "catppuccin-macchiato"   # Theme for dark mode
    lightTheme = "catppuccin-frappe"     # Theme for light mode

[outputs]
  home = ["HTML", "JSON"]